name: Actions 101

on:
  push

jobs:
  hello_world:
    name: Hello World!
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Run Script
      run: echo Hello, try Swift!

  lint:
      name: Swiftlint
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@master
      
      - name: Install Swiftlint
        run: |
          brew install swiftlint
          swiftlint autocorrect
          echo Linting done!
  # this is the step to build my app
  build:
    name: Build My App
    runs-on: macos-latest
    needs: lint
    steps:
    - uses: actions/checkout@master
    
    - name: Choose Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app
      
    - name: Build App
      run: xcodebuild -scheme "ScoreKeeper" -target ScoreKeeper -sdk iphonesimulator clean build
