#name: Main Branch Pipeline
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  ios_build:
#    name: Build for iOS
#    runs-on: macos-10.15
#    steps:
#    - uses: actions/checkout@main
#
#    - name: Inject staging configuration
#      run: ./inject-staging.sh ${{ secrets.MS_APP_CENTER_SECRET_STAGING}} ${{ secrets.MS_APP_CENTER_URL_SCHEME_STAGING }} ${{ secrets.STAGING_ROOT_URL }} ${{ secrets.HTTPS_SCHEME }} ${{ secrets.STAGING_APP_NAME }} ${{ secrets.STAGING_APP_BUNDLE_ID }}
#
#    - name: Decrypt secrets
#      run: ./decrypt-secrets.sh ${{ secrets.IOS_KEYS_SECRET }}
#
#    - name: Clean & Build App
#      run: ./build-app-staging.sh
